# Generated by Django 2.0.5 on 2018-05-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InitNetworkInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('eth_ip_address', models.CharField(max_length=50)),
                ('eth_mask', models.CharField(max_length=50)),
                ('wlan_ip_address', models.CharField(max_length=50)),
                ('wlan_mask', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=50)),
                ('domain_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('server_name', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=50)),
                ('folder_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UpdatedNetworkInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('eth_ip_address', models.CharField(max_length=50)),
                ('eth_mask', models.CharField(max_length=50)),
                ('wlan_ip_address', models.CharField(max_length=50)),
                ('wlan_mask', models.CharField(max_length=50)),
            ],
        ),
    ]
