# Generated by Django 2.0.5 on 2018-05-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebHMI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherSettingsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('uprating_rate_min', models.CharField(max_length=50)),
                ('uprating_rate_sec', models.CharField(max_length=50)),
                ('account_id', models.CharField(max_length=50)),
                ('account_pw', models.CharField(max_length=50)),
                ('auth_product', models.CharField(max_length=50)),
                ('auth_serial', models.CharField(max_length=50)),
            ],
        ),
    ]
