# Generated by Django 2.0.5 on 2018-06-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebHMI', '0003_othersettingsinfo_auth_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatednetworkinfo',
            name='wlan_gateway',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
