# Generated by Django 2.0.6 on 1970-01-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebHMI', '0004_updatednetworkinfo_wlan_gateway'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
