# Generated by Django 2.0.6 on 2018-07-24 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebHMI', '0006_auto_19700101_0933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
